version: '3'
services:
  server:
    build:
      context: ./src/server
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    container_name: server_container

  client:
    build:
      context: ./src/client
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3
    container_name: client_container
    depends_on:
      - server

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24
